import 'dart:typed_data';

import 'package:flutter/foundation.dart';

import '../../sdk.dart';

/// A data class to hold the properties of a single font defined in the font table.
///
/// This includes metadata for the font definition in `fontTable.xml`.
/// It can also include references to embedded font files for regular, bold, italic,
/// or bold-italic variants.
class FontProperties {
  const FontProperties({
    required this.name,
    this.altName,
    this.panose1,
    this.charset,
    this.family, // e.g., 'roman', 'swiss', 'script', 'auto'
    this.notTrueType,
    this.pitch, // e.g., 'fixed', 'variable'
    this.sigUsb0,
    this.sigUsb1,
    this.sigUsb2,
    this.sigUsb3,
    this.sigCsb0,
    this.sigCsb1,
    this.embedRegular, // Reference to embedded regular font
    this.embedBold, // Reference to embedded bold font
    this.embedItalic, // Reference to embedded italic font
    this.embedBoldItalic, // Reference to embedded bold-italic font
    this.fontBinaryData, // Binary data if this font is to be embedded (used by FontStore)
  });

  /// Creates [FontProperties] for a font that is to be embedded within the DOCX.
  ///
  /// This simplifies the creation process by pre-populating common signature,
  /// family, and pitch settings, and includes the binary font data.
  ///
  /// [name] The actual name of the font (e.g., "Arial").
  /// [bytes] The actual binary data of the font file.
  /// [originalExtension] The original file extension of the font (e.g., 'ttf', 'otf').
  /// [characterSet] The character set of the font. Defaults to `CharacterSet.ansi`.
  /// [altName] An optional alternative name for the font.
  /// [panose1], [family], [pitch], [sig...] for metadata.
  /// [fontKey] An optional GUID used for font obfuscation. If not provided, a new one will be generated by [FontStore].
  factory FontProperties.embedded({
    required String name,
    required Uint8List bytes,
    required String originalExtension,
    CharacterSet characterSet = CharacterSet.ansi,
    String? altName,
    String? panose1,
    String? family,
    String? pitch,
    String? sigUsb0,
    String? sigUsb1,
    String? sigUsb2,
    String? sigUsb3,
    String? sigCsb0,
    String? sigCsb1,
    String? fontKey,
  }) {
    return FontProperties(
      name: name,
      altName: altName,
      //NOTE: i need to search about what means panose1
      // since i dont get it too much about this configs
      panose1: panose1 ?? '020F0502020204030204',
      charset: characterSet,
      family: family ?? 'auto',
      pitch: pitch ?? 'variable',
      sigUsb0: sigUsb0,
      sigUsb1: sigUsb1,
      sigUsb2: sigUsb2,
      sigUsb3: sigUsb3,
      sigCsb0: sigCsb0,
      sigCsb1: sigCsb1,
      fontBinaryData: FontBinaryData(
        fontKey: fontKey ?? uuidV4.generate(),
        bytes: bytes,
        extension: originalExtension,
      ),
    );
  }

  /// Creates [FontProperties] for a font that is *not* embedded,
  /// but merely referenced by name in the document.
  /// Word will attempt to use a locally installed font or a fallback.
  factory FontProperties.referenced({
    required String name,
    CharacterSet characterSet = CharacterSet.ansi,
    String? altName,
    String? panose1,
    String? family,
    String? pitch,
    String? sigUsb0,
    String? sigUsb1,
    String? sigUsb2,
    String? sigUsb3,
    String? sigCsb0,
    String? sigCsb1,
    bool? notTrueType, // Also allow for referenced fonts to specify this
  }) {
    return FontProperties(
      name: name,
      altName: altName,
      panose1: panose1,
      charset: characterSet,
      family: family,
      pitch: pitch,
      notTrueType: notTrueType,
      sigUsb0: sigUsb0,
      sigUsb1: sigUsb1,
      sigUsb2: sigUsb2,
      sigUsb3: sigUsb3,
      sigCsb0: sigCsb0,
      sigCsb1: sigCsb1,
      fontBinaryData: null, // Not embedded
      embedRegular: null, // Not applicable for referenced fonts
    );
  }

  final String name;
  final String? altName;
  final String? panose1;
  final CharacterSet? charset;
  final String? family;
  final bool? notTrueType;
  final String? pitch;
  final String? sigUsb0;
  final String? sigUsb1;
  final String? sigUsb2;
  final String? sigUsb3;
  final String? sigCsb0;
  final String? sigCsb1;

  /// Reference to the embedded regular font file. This is populated by [FontStore].
  final EmbeddedFontRefOptions? embedRegular;

  /// Reference to the embedded bold font file. This is populated by [FontStore].
  final EmbeddedFontRefOptions? embedBold;

  /// Reference to the embedded italic font file. This is populated by [FontStore].
  final EmbeddedFontRefOptions? embedItalic;

  /// Reference to the embedded bold-italic font file. This is populated by [FontStore].
  final EmbeddedFontRefOptions? embedBoldItalic;

  /// Binary data for the font if it's an embedded font.
  /// This is used internally by [FontStore] to add the font binary to the archive.
  final FontBinaryData? fontBinaryData;

  FontProperties copyWithEmbeddedRef({
    EmbeddedFontRefOptions? embedRegular,
    EmbeddedFontRefOptions? embedBold,
    EmbeddedFontRefOptions? embedItalic,
    EmbeddedFontRefOptions? embedBoldItalic,
  }) {
    return FontProperties(
      name: name,
      altName: altName,
      panose1: panose1,
      charset: charset,
      family: family,
      notTrueType: notTrueType,
      pitch: pitch,
      sigUsb0: sigUsb0,
      sigUsb1: sigUsb1,
      sigUsb2: sigUsb2,
      sigUsb3: sigUsb3,
      sigCsb0: sigCsb0,
      sigCsb1: sigCsb1,
      embedRegular: embedRegular ?? this.embedRegular,
      embedBold: embedBold ?? this.embedBold,
      embedItalic: embedItalic ?? this.embedItalic,
      embedBoldItalic: embedBoldItalic ?? this.embedBoldItalic,
      fontBinaryData: fontBinaryData, // Keep existing binary data
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! FontProperties) return false;

    return name == other.name &&
        altName == other.altName &&
        panose1 == other.panose1 &&
        charset == other.charset &&
        family == other.family &&
        notTrueType == other.notTrueType &&
        pitch == other.pitch &&
        sigUsb0 == other.sigUsb0 &&
        sigUsb1 == other.sigUsb1 &&
        sigUsb2 == other.sigUsb2 &&
        sigUsb3 == other.sigUsb3 &&
        sigCsb0 == other.sigCsb0 &&
        sigCsb1 == other.sigCsb1 &&
        embedRegular == other.embedRegular &&
        embedBold == other.embedBold &&
        embedItalic == other.embedItalic &&
        embedBoldItalic == other.embedBoldItalic &&
        fontBinaryData == other.fontBinaryData;
  }

  @override
  int get hashCode => Object.hashAll([
        name,
        altName,
        panose1,
        charset,
        family,
        notTrueType,
        pitch,
        sigUsb0,
        sigUsb1,
        sigUsb2,
        sigUsb3,
        sigCsb0,
        sigCsb1,
        embedRegular,
        embedBold,
        embedItalic,
        embedBoldItalic,
        fontBinaryData,
      ]);
}

/// Options for an embedded font reference within the `<w:font>` element
/// (e.g., for `<w:embedRegular>`, `<w:embedBold>`).
class EmbeddedFontRefOptions {
  const EmbeddedFontRefOptions({
    required this.rId,
    this.fontKey,
    this.subsetted,
  });

  /// The relationship ID (`r:id`) to the embedded font binary in `fontTable.xml.rels`.
  final String rId;

  /// The Embedded Font Obfuscation Key (GUID).
  final String? fontKey;

  /// Indicates if the embedded font is subsetted.
  final bool? subsetted;

  // Method to copy and update rId/fontKey if needed by FontStore
  EmbeddedFontRefOptions copyWith({
    String? rId,
    String? fontKey,
    bool? subsetted,
  }) {
    return EmbeddedFontRefOptions(
      rId: rId ?? this.rId,
      fontKey: fontKey ?? this.fontKey,
      subsetted: subsetted ?? this.subsetted,
    );
  }

  @override
  bool operator ==(Object other) {
    if (other is! EmbeddedFontRefOptions) return false;
    if (identical(this, other)) return true;
    return fontKey == other.fontKey &&
        rId == other.rId &&
        subsetted == other.subsetted;
  }

  @override
  int get hashCode => Object.hash(
        fontKey,
        rId,
        subsetted,
      );
}

/// Represents the character set options for a font.
enum CharacterSet {
  ansi('00'),
  common('01'),
  symbol('02'),
  mac('4D'),
  jis('80'),
  hangul('81'),
  johab('82'),
  gb2312('86'),
  chineseBig5('88'),
  greek('A1'),
  turkish('A2'),
  vietnamese('A3'),
  hebrew('B1'),
  arabic('B2'),
  baltic('BA'),
  russian('CC'),
  thai('DE'),
  eastEurope('EE'),
  oem('FF');

  const CharacterSet(this.value);

  static CharacterSet? getFromStr(String str) {
    for (final CharacterSet v in values) {
      if (v.name == str) {
        return v;
      }
    }
    return null;
  }

  final String value;
}

/// Represents the binary data and obfuscation key for an embedded font.
class FontBinaryData {
  const FontBinaryData({
    required this.fontKey,
    required this.bytes,
    required this.extension,
  });

  /// The GUID used for font obfuscation (w:fontKey).
  final String fontKey;

  /// The raw bytes of the font file.
  final Uint8List bytes;

  /// The file extension of the font (e.g., 'ttf', 'otf').
  final String extension;

  @override
  bool operator ==(Object other) {
    if (other is! FontBinaryData) return false;
    if (identical(this, other)) return true;
    return fontKey == other.fontKey &&
        extension == other.extension &&
        listEquals(bytes, other.bytes);
  }

  @override
  int get hashCode => Object.hash(
        fontKey,
        bytes.map(
          (int n) => n.hashCode,
        ),
        extension,
      );
}
