import '../../../../sdk.dart';
import '../../pipeline_context.dart';
import '../../pipeline_stage.dart';

/// Stage that resolves the theme ID.
///
/// If [PipelineConfig.applyCustomTheme] is true, this stage looks for
/// the theme ID generated by [DocumentRelsBuildStage] and stores it
/// for use in [DocumentBuildStage] (XmlBodyComponent).
///
/// The theme ID is extracted from the XmlDocumentRelsComponent
/// that is built during relationship building.
///
/// This stage runs AFTER DocumentRelsBuildStage.
class ThemeResolutionStage extends PipelineStage {
  const ThemeResolutionStage();

  @override
  String get name => 'ThemeResolution';

  @override
  int get order => 5;

  @override
  StageCategory get category => StageCategory.processing;

  @override
  String get description => 'Resolves theme ID if custom theme is applied.';

  @override
  bool shouldExecute(PipelineContext context) {
    return !context.flags.skipTheme && context.config.applyCustomTheme;
  }

  @override
  void execute(PipelineContext context) {
    CompilerLogger.root.debug(
      'Theme resolution stage: theme will be resolved during DocumentRelsBuildStage.',
    );

    // Store flag to indicate theme is enabled
    context.metadata['themeEnabled'] = true;
  }
}
