import 'package:meta/meta.dart';

import '../sdk.dart';

/// Represent the styles of the document
class Style extends IterableConfigurators {
  Style({
    required this.type,
    required this.styleId,
    required this.styleName,
    this.defaultValue,
    super.configurators = const <StyleConfigurator>[],
    String? id,
  })  : isAutoGenerated = id == null,
        id = id ?? nanoid(3),
        _onlyReference = false;

  /// Creates a Style instance for searching purposes
  Style.reference(this.styleId)
      : type = '',
        styleName = '',
        isAutoGenerated = false,
        id = nanoid(3),
        defaultValue = null,
        _onlyReference = true,
        super(
          configurators: const <StyleConfigurator>[],
        );

  factory Style.invalid() {
    return Style(
      type: 'invalid',
      styleId: 'invalid',
      styleName: 'invalid',
    );
  }

  static const String paragraphType = 'paragraph';
  static const String characterType = 'character';

  bool _onlyReference = false;

  bool get isReference => _onlyReference;

  bool get isInvalid =>
      styleId == 'invalid' && styleName == 'invalid' && type == 'invalid';

  @internal
  final bool isAutoGenerated;

  // the internal identifier of this style
  late String id;
  final String type;

  /// Represents the id that will be used by the XmlNodes
  /// of Word to applies any existent style in style.xml
  final String styleId;
  final Object? defaultValue;

  /// This is the name of the style that
  /// will be showed by the Word Editor
  final String styleName;

  Style? getStyleWhereBaseOn(DocumentStylesSheet styles) {
    final StyleConfigurator? basedOnConfigurator =
        getConfiguratorOrNull('w:basedOn');
    if (basedOnConfigurator == null) return null;
    final Style? style =
        styles.getStyleById(basedOnConfigurator.value as String);
    if (style == null) return null;
    assert(style.styleId == basedOnConfigurator.value, '');
    return style;
  }

  /// Returns the final style version this style using
  /// w:basedOn mark as the way to get the other properties
  Style getDeepStyleRelation(DocumentStylesSheet styles) {
    const int maxAttemps = 200;
    final List<Style> styleHierarchy = [this];
    Style? currentStyleInChain = this;
    int attemp = 0;

    // Build the hierarchy from the most base style up to the current style.
    // Insert at the beginning to have the oldest ancestor first.
    while (currentStyleInChain!.basedOn != null && attemp < maxAttemps) {
      final Style? basedOn =
          styles.getStyleById(currentStyleInChain.basedOn!.value as String);
      if (basedOn != null &&
          !styleHierarchy.any(
            (Style s) => s.id == basedOn.id,
          )) {
        styleHierarchy.insert(0, basedOn);
        currentStyleInChain = basedOn;
      } else {
        break; // No more base styles or detected a loop
      }
      attemp++;
    }

    // Initialize merged properties maps for top-level, paragraph properties (pPr),
    // and run properties (rPr).
    final Map<String, StyleConfigurator> mergedTopLevelConfigurators = {};
    final Map<String, StyleConfigurator> mergedPPrChildren = {};
    final Map<String, StyleConfigurator> mergedRPrChildren = {};

    // Helper to convert an iterable of StyleConfigurator to a map for easier merging.
    Map<String, StyleConfigurator> listToMap(
            Iterable<StyleConfigurator> list) =>
        {
          for (final c in list) c.qualifiedName: c,
        };

    // Recursive helper to merge children configurators.
    // It takes a base map and a list of overrides, returning a new merged map.
    Map<String, StyleConfigurator> mergeChildren(
      Map<String, StyleConfigurator> base,
      Iterable<StyleConfigurator> overrides,
    ) {
      final Map<String, StyleConfigurator> result =
          Map<String, StyleConfigurator>.from(base);
      //TODO: we need to take a look why on test, some parts are not being applied
      for (final StyleConfigurator overrideConfig in overrides) {
        final StyleConfigurator? existingConfig =
            result[overrideConfig.qualifiedName];
        if (existingConfig != null &&
            existingConfig.hasChildren &&
            overrideConfig.hasChildren) {
          // If both are containers, recursively merge their children.
          final Map<String, StyleConfigurator> mergedInnerChildren =
              mergeChildren(
            listToMap(existingConfig.configurators),
            overrideConfig.configurators,
          );
          // Create a new StyleConfigurator for the merged container.
          // Its value and attributes are taken from the overrideConfig.
          result[overrideConfig.qualifiedName] =
              StyleConfigurator.noSelfClosing(
            propertyName: overrideConfig.propertyName,
            prefix: overrideConfig.prefix,
            value: overrideConfig.value,
            attributes: overrideConfig.attributes,
            configurators: mergedInnerChildren.values.toList(),
          );
        } else {
          // Otherwise, simply replace the existing configurator or add the new one.
          result[overrideConfig.qualifiedName] = overrideConfig;
        }
      }
      return result;
    }

    // Iterate through the style hierarchy (from base to current) and merge properties.
    for (final Style style in styleHierarchy) {
      for (final StyleConfigurator config in style.configurators) {
        if (config.qualifiedName == 'w:basedOn' ||
            config.qualifiedName == 'w:rsId') {
          continue;
        }

        if (config.qualifiedName == xmlParagraphBlockAttrsNode) {
          // Merge children of w:pPr
          mergedPPrChildren.addAll(mergeChildren(
            mergedPPrChildren,
            config.configurators,
          ));
        } else if (config.qualifiedName == xmlParagraphInlineAttsrNode) {
          // Merge children of w:rPr
          mergedRPrChildren.addAll(mergeChildren(
            mergedRPrChildren,
            config.configurators,
          ));
        } else {
          // For other top-level configurators, the more specific style overrides.
          mergedTopLevelConfigurators[config.qualifiedName] = config;
        }
      }
    }

    // Construct the final list of configurators for the new Style instance.
    final List<StyleConfigurator> finalConfigurators =
        mergedTopLevelConfigurators.values.toList();

    // Add the merged w:pPr and w:rPr back as top-level configurators if they exist.
    if (mergedPPrChildren.isNotEmpty) {
      finalConfigurators.add(
        StyleConfigurator.noSelfClosing(
          prefix: 'w',
          propertyName: 'pPr',
          configurators: mergedPPrChildren.values.toList(),
        ),
      );
    }
    if (mergedRPrChildren.isNotEmpty) {
      finalConfigurators.add(
        StyleConfigurator.noSelfClosing(
          prefix: 'w',
          propertyName: 'rPr',
          configurators: mergedRPrChildren.values.toList(),
        ),
      );
    }

    // Create and return a new Style instance with all combined properties.
    // The top-level metadata (type, styleId, styleName, defaultValue, id)
    // should originate from the style on which this method was called (`this`).
    return Style(
      type: type,
      styleId: styleId,
      styleName: styleName,
      defaultValue: defaultValue,
      configurators: finalConfigurators,
      id: id,
    );
  }

  String toPrettyString() {
    return 'Style => $id\n'
        'Type: ${type.isEmpty ? 'no-type' : type},\n'
        'StyleId: $styleId, '
        '${defaultValue != null ? '' : 'Default value: $defaultValue, '}'
        'Style name: $styleName\n'
        'SubStyles: ${configurators.join('\n')}\n';
  }

  @override
  String toString() {
    return 'Style($id, '
        '${type.isEmpty ? 'no-type' : type}, '
        '$styleId, '
        'Style name: $styleName => [$configurators]';
  }

  String toXmlString() {
    final String xmlChildren = configurators
        .map(
          (StyleConfigurator c) => c.toXmlString(),
        )
        .join();
    return ' <w:style type="$type" w:styleId="$styleId">$xmlChildren</w:style>';
  }
}

class StyleConfigurator extends IterableConfigurators {
  /// Returns a StyleConfigurator that tells to the parser that this should contain only a start XmlNode to define the style
  ///
  /// ```xml
  ///  <w:spacing />
  /// ```
  StyleConfigurator.selfClosing({
    required this.propertyName,
    this.prefix,
    this.value,
    this.attributes,
  })  : isSelfClosing = true,
        super(configurators: const []);

  StyleConfigurator.invalid()
      : propertyName = 'invalid',
        prefix = '',
        value = null,
        attributes = null,
        isSelfClosing = false,
        super(configurators: const <StyleConfigurator>[]);

  /// Returns a StyleConfigurator that tells to the parser that this should be a start and end XmlNode between its children
  ///
  /// ```xml
  ///  <w:spacing>children</w:spacing>
  /// ```
  StyleConfigurator.noSelfClosing({
    required this.propertyName,
    this.prefix,
    this.value,
    this.attributes,
    super.configurators = const <StyleConfigurator>[],
  })  : isSelfClosing = false,
        assert(prefix == null || prefix.isNotEmpty, 'Prefix cannot be empty'),
        assert(
          propertyName.isNotEmpty,
          'propertyName cannot be empty',
        );

  final String propertyName;
  final String? prefix;
  final Object? value;
  // the attributes of the node
  final Map<String, dynamic>? attributes;
  final bool isSelfClosing;

  String get qualifiedName =>
      prefix == null ? propertyName : '$prefix:$propertyName';

  bool get isInvalid =>
      propertyName == 'invalid' ||
      propertyName.isEmpty &&
          value == null &&
          (attributes == null || attributes!.isEmpty) &&
          configurators.isEmpty &&
          isSelfClosing;
  bool get hasChildren => configurators.isNotEmpty;

  @override
  String toString() {
    return 'StyleConfigurator($prefix:$propertyName, $value, $attributes, ${configurators.map((n) => n.toString())})';
  }

  String toXmlString() {
    final String styleValue = value != null ? ' w:val="$value"' : '';
    final StringBuffer attributeBuffer = StringBuffer(styleValue);

    if (attributes != null && attributes!.isNotEmpty) {
      attributes!.forEach((key, val) {
        attributeBuffer.write(' $key="$val"');
      });
    }
    final String allAttributes = attributeBuffer.toString();

    final String xmlChildren = !hasChildren
        ? ''
        : configurators
            .map(
              (StyleConfigurator c) => c.toXmlString(),
            )
            .join();

    if (isSelfClosing) {
      return '<$qualifiedName$allAttributes/>';
    } else {
      return '<$qualifiedName$allAttributes>$xmlChildren</$qualifiedName>';
    }
  }
}

abstract class IterableConfigurators {
  IterableConfigurators({
    required this.configurators,
  });

  final Iterable<StyleConfigurator> configurators;

  StyleConfigurator? get link {
    if (configurators.isEmpty) return null;
    return configurators.firstWhere(
        (StyleConfigurator e) => e.propertyName == 'link',
        orElse: StyleConfigurator.invalid);
  }

  StyleConfigurator? get basedOn {
    if (configurators.isEmpty) return null;
    final StyleConfigurator result = configurators.firstWhere(
      (StyleConfigurator e) => e.qualifiedName == 'w:basedOn',
      orElse: StyleConfigurator.invalid,
    );
    return result.isInvalid ? null : result;
  }

  StyleConfigurator? get name {
    if (configurators.isEmpty) return null;
    return configurators.firstWhere(
        (StyleConfigurator e) => e.propertyName == 'name',
        orElse: StyleConfigurator.invalid);
  }

  StyleConfigurator? getConfiguratorOrNull(
    String matcher, {
    bool fullName = false,
  }) {
    final StyleConfigurator result = configurators.firstWhere(
        (StyleConfigurator e) => (fullName || matcher.contains(':')
            ? e.qualifiedName == matcher
            : e.propertyName == matcher),
        orElse: StyleConfigurator.invalid);
    return result.isInvalid ? null : result;
  }

  StyleConfigurator getConfigurator(String matcher, {bool fullName = false}) {
    if (configurators.isEmpty) return StyleConfigurator.invalid();
    return configurators.firstWhere(
        (StyleConfigurator e) => fullName || matcher.contains(':')
            ? e.qualifiedName == matcher
            : e.propertyName == matcher,
        orElse: StyleConfigurator.invalid);
  }

  Iterable<StyleConfigurator> findAllElements(String matcher) {
    if (configurators.isEmpty) return <StyleConfigurator>[];
    return configurators.where(
      (StyleConfigurator e) => matcher.contains(':')
          ? e.qualifiedName == matcher
          : e.propertyName == matcher,
    );
  }
}
