import 'package:xml/xml.dart';

import '../../../docx.dart';
import 'node_to_configurator.dart';
import 'string_ext.dart';

extension StyleToNode on Style {
  /// Converts a Style class into a valid XmlElement that can be used to putted into styles.xml file
  XmlElement? toNode({String prefix = ''}) {
    if (isInvalid) return null;
    final XmlElement xmlName = XmlElement.tag(
      'w:name',
      attributes: [
        XmlAttribute('w:val'.toName(), styleName),
      ],
    );
    return XmlElement.tag(
      'w:${prefix}style',
      attributes: [
        XmlAttribute('w:type'.toName(), type),
        XmlAttribute('w:styleId'.toName(), styleId),
        if (defaultValue != null)
          XmlAttribute('w:default'.toName(), defaultValue!.toString()),
      ],
      children: [
        // if does not have a name into its children, this add it
        if (name == null) xmlName,
        //TODO: we need to generate the other ids
        if (!isAutoGenerated)
          XmlElement.tag(
            'w:rsId',
            attributes: <XmlAttribute>[
              XmlAttribute(
                'w:val'.toName(),
                id,
              ),
            ],
          ),
        ...configurators.map(
          (
            StyleConfigurator configurator,
          ) =>
              configurator.toXmlNode,
        ),
      ],
      isSelfClosing: false,
    );
  }

  XmlElement? toReferenceNode({String prefix = 'r'}) {
    return XmlElement.tag(
      'w:${prefix}Style',
      attributes: [
        XmlAttribute(
          'w:val'.toName(),
          styleName,
        ),
      ],
      isSelfClosing: true,
    );
  }

  XmlElement? toParagraphStyleNode() {
    final StyleConfigurator runConfigs =
        getConfigurator(xmlParagraphBlockAttrsNode);
    if (runConfigs.isInvalid) return null;
    return XmlElement.tag(
      'w:pPr',
      children: [
        ...runConfigs.toNodes,
      ],
      isSelfClosing: false,
    );
  }

  XmlElement? toRunStyleNode() {
    final StyleConfigurator runConfigs =
        getConfigurator(xmlParagraphInlineAttsrNode);
    if (runConfigs.isInvalid) return null;
    //TODO: why we aren't returning the runConfigs directly?
    return XmlElement.tag(
      'w:rPr',
      children: [
        ...runConfigs.toNodes,
      ],
      isSelfClosing: false,
    );
  }

  List<XmlElement> toRunStyleNodes({
    bool shouldShowStyleRef = true,
    bool useConfigurators = true,
  }) {
    final StyleConfigurator runConfigs = !useConfigurators
        ? StyleConfigurator.invalid()
        : getConfigurator(
            xmlParagraphInlineAttsrNode,
            fullName: true,
          );

    return [
      if (shouldShowStyleRef)
        XmlElement.tag(
          xmlRunStyleNode,
          attributes: [
            XmlAttribute(
              'w:val'.toName(),
              styleName,
            ),
          ],
          isSelfClosing: true,
        ),
      if (useConfigurators) ...runConfigs.toNodes,
      // add values of the style
      if (useConfigurators)
        ...configurators
            .where((StyleConfigurator n) =>
                n.propertyName != runConfigs.propertyName)
            .map((StyleConfigurator n) => n.toXmlNode),
    ];
  }

  List<XmlElement> toParagraphStyleNodes({
    bool shouldShowStyleRef = true,
    bool useConfigurators = true,
  }) {
    final StyleConfigurator runConfigs = !useConfigurators
        ? StyleConfigurator.invalid()
        : getConfigurator(
            xmlParagraphBlockAttrsNode,
          );

    return [
      if (shouldShowStyleRef)
        XmlElement.tag(
          xmlParagraphStyleNode,
          attributes: [
            XmlAttribute(
              'w:val'.toName(),
              styleName,
            ),
          ],
          isSelfClosing: true,
        ),
      if (useConfigurators) ...runConfigs.toNodes,
      // add values of the style
      if (useConfigurators)
        ...configurators
            .where((n) => n.propertyName != runConfigs.propertyName)
            .map(
              (n) => n.toXmlNode,
            ),
    ];
  }
}
