import 'package:xml/xml.dart';

import '../../../docx.dart';
import 'node_to_configurator.dart';
import 'string_ext.dart';

extension StyleToNode on Style {
  /// Converts a Style class into a valid XmlElement that can be used to putted into styles.xml file
  XmlElement? toNode({String prefix = ''}) {
    if (isInvalid) return null;
    final XmlElement xmlName = XmlElement.tag(
      'w:name',
      attributes: [
        XmlAttribute('w:val'.toName(), styleName),
      ],
    );
    return XmlElement.tag(
      'w:${prefix}style',
      attributes: [
        XmlAttribute('w:type'.toName(), type),
        XmlAttribute('w:styleId'.toName(), styleId),
        if (defaultValue != null)
          XmlAttribute('w:default'.toName(), defaultValue!.toString()),
      ],
      children: [
        // if does not have a name into its children, this add it
        if (name == null) xmlName,
        if (!isAutoGenerated)
          XmlElement.tag(
            'w:rsId',
            attributes: <XmlAttribute>[
              XmlAttribute('w:val'.toName(), id),
            ],
          ),
        ...configurators.map(
          (configurator) => configurator.toXmlNode,
        ),
      ],
      isSelfClosing: false,
    );
  }

  XmlElement? toReferenceNode({String prefix = 'r'}) {
    return XmlElement.tag(
      'w:${prefix}Style',
      attributes: [
        XmlAttribute(
          'w:val'.toName(),
          styleName,
        ),
      ],
      isSelfClosing: true,
    );
  }

  List<XmlElement> toRunStyleNodes() {
    final StyleConfigurator runConfigs = getConfigurator(
      xmlParagraphInlineAttsrNode,
      fullName: true,
    );

    return [
      XmlElement.tag(
        xmlRunStyleNode,
        attributes: [
          XmlAttribute(
            'w:val'.toName(),
            styleName,
          ),
        ],
        isSelfClosing: true,
      ),
      ...runConfigs.toNodes,
      // add values of the style
      ...configurators
          .where((n) => n.propertyName != runConfigs.propertyName)
          .map(
            (n) => n.toXmlNode,
          ),
    ];
  }

  List<XmlElement> toBlockStyleNodes() {
    final StyleConfigurator runConfigs =
        getConfigurator(xmlParagraphBlockAttrsNode);

    return [
      XmlElement.tag(
        xmlParagraphStyleNode,
        attributes: [
          XmlAttribute(
            'w:val'.toName(),
            styleName,
          ),
        ],
        isSelfClosing: true,
      ),
      ...runConfigs.toNodes,
      // add values of the style
      ...configurators
          .where((n) => n.propertyName != runConfigs.propertyName)
          .map(
            (n) => n.toXmlNode,
          ),
    ];
  }
}
